name: Check common
on:
  pull_request:
    branches:
      - develop

jobs:
  check_nix:
    name: Check for nix platforms (Linux)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check
        run: gradle -si check
  check_windlows:
    name: Check for windows platform
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check
        run: gradle -si check
